name: safacw
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  flutter_session: ^0.1.1
  http: ^0.13.4
  intl: ^0.17.0
  provider: ^6.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - lib/lang/

  fonts:
  - family: JosefinSans
    fonts:
      - asset: assets/fonts/JosefinSans-ExtraLight.ttf
        weight: 100
      - asset: assets/fonts/JosefinSans-Light.ttf
        weight: 300
      - asset: assets/fonts/JosefinSans-Medium.ttf
        weight: 400
      - asset: assets/fonts/JosefinSans-Regular.ttf
        weight: 500
      - asset: assets/fonts/JosefinSans-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/JosefinSans-Bold.ttf
        weight: 900
