name: safacw
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  flutter_session: ^0.1.1
  geocoding: ^1.0.5
  geolocator: ^6.2.1

  google_maps_flutter: ^2.0.10
  http: ^0.13.4
  intl: ^0.17.0
  lottie: ^1.4.3
  provider: ^6.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/lang/
    - assets/images/
  # fonts:
  #   - family: JosefinSans
  #     fonts:
  #       - asset: assets/fonts/JosefinSans-ExtraLight.tff
  #         weight: 100
  #       - asset: assets/fonts/JosefinSans-Light.tff
  #         weight: 300
  #       - asset: assets/fonts/JosefinSans-Medium.tff
  #         weight: 400
  #       - asset: assets/fonts/JosefinSans-Regular.tff
  #         weight: 500
  #       - asset: assets/fonts/JosefinSans-SemiBold.tff
  #         weight: 800
  #       - asset: assets/fonts/JosefinSans-Bold.tff
  #         weight: 900
