# Generated by Django 4.0.3 on 2022-09-16 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carwash', '0009_item_both_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='service_provider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9999),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9999),
        ),
        migrations.AlterField(
            model_name='item',
            name='both',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='in_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='out_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.DecimalField(blank=True, decimal_places=2, max_digits=9999, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=2, max_digits=9999, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
