# Generated by Django 4.0.3 on 2022-09-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0010_order_driver_order_service_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_provider',
        ),
        migrations.DeleteModel(
            name='location',
        ),
    ]
