# Generated by Django 4.0.3 on 2022-09-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0011_remove_order_driver_remove_order_service_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
