# Generated by Django 4.0.3 on 2022-09-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0016_alter_order_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
