# Generated by Django 4.0.3 on 2022-11-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0017_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='profile',
            name='Service_provider_type',
            field=models.CharField(choices=[('Laundry', 'Laundry'), ('CarWash', 'CarWash'), ('BuildingCleaning', 'BuildingCleaning')], default='BuildingCleaning', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Type',
            field=models.CharField(choices=[('1', 'CUSTOMER'), ('2', 'DRIVER'), ('3', 'SERVICE_PROVIDER')], default='3', max_length=2),
        ),
    ]
